version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - staticcheck
    - govet
    - errcheck
    - errorlint
    - nilerr
    - ineffassign
    - wastedassign
    - bodyclose
    - sqlclosecheck
    - unused 
    - revive
    - gocritic
    - goconst
    - whitespace
    - wsl_v5
    - nolintlint
    - godot
    - canonicalheader
    - dupword
    - funlen
    - gocyclo
    - gocognit
    - importas
    - nakedret
    - tagalign
    - ireturn
    - copyloopvar
    - noctx
    - durationcheck
    - fatcontext
    - iface
    - makezero
    - unconvert
    - asasalint
    - exptostd
    - goheader
    - intrange
    - mirror
    - usestdlibvars
    - usetesting
    - prealloc
    - perfsprint
    - gosec
    - tparallel
    - thelper
    - testifylint
    - misspell

  settings:
    goimports:
      local-prefixes: github.com/0x5w4/go-app-template/
    gocognit:
      min-complexity: 30
    gocyclo:
      min-complexity: 30
    funlen:
      lines: 80
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    godot:
      scope: toplevel
    nakedret:
      max-func-lines: 30
    revive:
      confidence: 0.8
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      force-err-cuddling: true
    goheader:
    importas:
    gosec:
      excludes:
        - G101 
        - G404 
        - G501 
    testifylint:
      expected-actual:
        pattern: "^(exp|want)"
      go-require:
        ignore-http-handlers: true
    misspell:
      locale: US
    tagalign:
      align: true
      sort: true
      order:
        - json
        - yaml
        - xml
        - toml
        - bson
        - db
        - validate

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: true
  exclude-dirs-use-default: true
  exclude-files:
    - ".*\\.gen\\.go"
    - ".*_mock\\.go"
    - ".*\\.pb\\.go"
  exclude-rules:
    - path: _test\.go|.*_gen\.go|.*\.pb\.go
      linters:
        - funlen
        - gocyclo
        - gocognit
        - gosec
    - path: _test\.go
      text: "comment on exported function"
      linters:
        - revive
    - path: _test\.go
      text: "G104: Errors unhandled"
      linters:
        - gosec

output:  
  formats:
    text:
      path: ./reports/golangci-lint.txt
      print-linter-name: false
      print-issued-lines: false
      colors: false
    json:
      path: ./reports/golangci-lint.json
    tab:
      path: ./reports/golangci-lint.txt
      print-linter-name: true
      colors: false
    html:
      path: ./reports/golangci-lint.html
    checkstyle:
      path: ./reports/golangci-lint.xml
    code-climate:
      path: ./reports/golangci-lint.json
    junit-xml:
      path: ./reports/golangci-lint.xml
      extended: true
    teamcity:
      path: ./reports/golangci-lint.txt
    sarif:
      path: ./reports/golangci-lint.json
  path-prefix: ""
  path-mode: "abs"
  sort-order:
    - linter
    - severity
    - file
  show-stats: false

severity:
  default: error
  rules: