run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    # Core correctness
    - errcheck
    - govet
    - staticcheck
    - copyloopvar
    - ireturn

    # Style & maintainability
    - revive
    - gosimple
    - gocritic
    - gocyclo
    - gocognit
    - goconst
    - whitespace
    - wsl
    - nolintlint
    - errorlint

    # Formatting
    - gofmt
    - goimports
    - misspell

    # Performance & code quality
    - ineffassign
    - wastedassign
    - prealloc
    - unconvert
    - usestdlibvars
    - makezero
    - asasalint

    # Security
    - gosec
    - bodyclose
    - sqlclosecheck
    - noctx
    - durationcheck
    - nilerr

    # Testing
    - tparallel
    - thelper

linters-settings:
  goimports:
    local-prefixes: github.com/0x5w4/go-app-template/
  gocyclo:
    min-complexity: 30
  gocognit:
    min-complexity: 30
  misspell:
    locale: US
  wsl:
    force-case-trailing-whitespace: 0
    allow-trailing-comment: true
    allow-cuddle-declarations: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: true
  exclude-dirs-use-default: true
  exclude-files:
    - ".*\\.gen\\.go"   
    - ".*_mock\\.go"
    - ".*\\.pb\\.go"
  exclude-rules:
    - path: _test\.go|.*_gen\.go|.*\.pb\.go
      linters:
        - funlen
        - gocyclo
        - gocognit
        - gosec
        - dupl
    - path: _test\.go
      text: "comment on exported function"
      linters:
        - revive
    - path: _test\.go
      text: "G104: Errors unhandled"
      linters:
        - gosec

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  path-prefix: ""
